author: Amaan Qureshi (amaanq12@gmail.com)
license:
  header: |

    This file is part of the CLI application APK Updater.

    This project, APK Updater, is not to be redistributed or copied without

    the express permission of the copyright holder, Amaan Qureshi (amaanq).
  text: |
    {{ .copyright }}

    This project, APK Updater, is not to be redistributed or copied without

    the express permission of the copyright holder, Amaan Qureshi (amaanq).
useViper: true
